import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Outfit } from "next/font/google";
import { Cabin } from "next/font/google";
import { Manrope } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400"],
});

const cabin = Cabin({
  subsets: ["vietnamese"],
  weight: ["400"],
});

const manrope = Manrope({
  subsets: ["vietnamese"],
  // weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#fdfdfc]`}>{children}</body>
    </html>
  );
}
